spring:
  liquibase:
    url: jdbc:postgresql://127.0.0.1:5432/testdb
    user: postgres
    password: postgres
    change-log: classpath:/db/db.changelog-master.yml
    enabled: true
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/testdb
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update